// <auto-generated />
namespace Rib.Ef.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CommentsAndUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentsAndUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201603290619055_CommentsAndUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
