// <auto-generated />
namespace Rib.Ef.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SqlGeneratedOnCreatedOnUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SqlGeneratedOnCreatedOnUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201603301927169_SqlGeneratedOnCreatedOnUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
